//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class lista_registros
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string plazo { get; set; }
        public Nullable<int> dias_plazo { get; set; }
        public string Moneda_ColumnaC { get; set; }
        public string Moneda_ColumnaE { get; set; }
        public Nullable<double> ASK_monedaC { get; set; }
        public Nullable<double> ASK_monedaE { get; set; }
        public Nullable<double> BID_monedaC { get; set; }
        public Nullable<double> BID_monedaE { get; set; }
    }
}
